### PR TITLE
Plain js objects now work with subtemplate

### PR DESCRIPTION
**Pull request by cherifGsoul**
Fixes https://github.com/canjs/can-stache/issues/208

### CODE REVIEW

**Comment by cherifGsoul** [comment]
@phillipskevin can you check why the check failed? all the tests pass for me!!

**Comment by phillipskevin** [comment]
It failed for me locally. I think you need to merge/rebase master in to your branch.

**Comment by cherifGsoul** [comment]
@phillipskevin thank you :)

**Comment by cherifGsoul** [comment]
It seems this can be merged!

**Comment by cherifGsoul** [comment]
cc @justinbmeyer

**Comment by cherifGsoul** [comment]
No problem @phillipskevin :+1:

**Pull request merged**
