### PR TITLE
@arg's functions not executed

### LINKED ISSUE #172: {{#if @expr}} evaluates the function and checks the returned value
When using ```{{#if @func}}``` to render a subtree, the function referenced is called and the return value checked though I expect to just be doing a truthy check to see if the function exists in the scope.

See: http://jsbin.com/mikoqidesa/1/edit?html,console,output

This issue effects can-stache included in CanJS 2.3 and the current 3.5.x release.

### PR DESCRIPTION
**Pull request by christopherjbaker**
closes #172. Using "{{@func}}" or "{{#if @func}}" had been executing the function and using its value, rather than the function itself. (Actually, it appears that the first case was incidentally fixed in v3.0.21.)

I think there might be a better way to solve this, though I am unsure what it is. As best I can tell, because `if` always executes the [provided function](https://github.com/canjs/can-stache/blob/master/helpers/core.js#L153), the it needed to be changed to be one that validates the existence of the function, rather than the function itself.

### CODE REVIEW

**Comment by christopherjbaker** [comment]
The second half of the fix (`{{@func}}`) is now in. I am using the same sort of logic as before.

MustacheCore assumes that a function [should always be executed](https://github.com/canjs/can-stache/blob/master/src/mustache_core.js#L344) as a helper, precluding the (albeit unlikely) possibility of function as a value. If the function is preceded by an `@`, it will treat it as a value, rather than a function.

**Comment by christopherjbaker** [comment]
@justinbmeyer I modified both places to use `value && value.isComputed` as we discussed, though that didn't fix the problem. The [`expr` passed in](https://github.com/canjs/can-stache/blob/master/helpers/core.js#L153) is in fact a compute, which evaluates to the function. This gets passed into [compute.truthy](https://github.com/canjs/can-compute/blob/master/can-compute.js#L89), which (again) evaluates all functions. If I switch this also to `res && res.isComputed` it works without my original fix. I don't know what the greater implications of this would be, though, as that seems to be changing a very deep functionality.

**Comment by justinbmeyer** [comment]
@christopherjbaker If you run `canjs/canjs`'s tests with https://github.com/canjs/can-compute/blob/master/can-compute.js#L88 looking like:

```js
return COMPUTE(function () {
		var res = compute();
		return !!res;
	});
```

What happens? 

If nothing breaks, we can probably update `truthy` to look like this.  It's not a documented API.  If it breaks other tests, we can decide to update it to look like this, or probably create our own version for use by `#if`

**Comment by christopherjbaker** [comment]
Alright, this is ready, though it is dependent upon canjs/can-compute#75, and the travis CI tests here won't pass till it can install those changes.

Since this fix introduces a dependency in a specific version of can-compute, I presume we need to alter something? or even delay till a minor release?

**Comment by christopherjbaker** [comment]
Woo, it's fixed!

**Pull request merged**
