### PR TITLE
Add #not helper as inverse of #is

### PR DESCRIPTION
**Pull request by imjoshdean**
I've run into more than one situation where I need something like this but don't want to write out

```html
{{#is expr1 expr2}}
    {{! nothing here}}
{{else}}
    <p>Something</p>
{{/is}}
```

We have an inverse of `{{#if}}` by way of `{{#unless}}`, I'm surprised we've not made one for `{{#eq}}` now `{{#is}}`. I would suspect it was just oversight, but here we are.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Use ^

**Comment by imjoshdean** [comment]
Alright, this probably could stand to have better documentation then. Looking over the API this morning, I think I'm *supposed* to infer that you can do `{{^is}}` from https://canjs.com/doc/can-stache.tags.inverse.html but we don't explicitly state that this is something you can do anywhere.

**Comment by imjoshdean** [comment]
I also still think this should be added. Either that or `{{#unless}}` should be deprecated.

**Comment by justinbmeyer** [comment]
Why would `#unless` need to be deprecated?

**Pull request closed without merging**
