### PR TITLE
WIP: passing nodeList to live.attr

### PR DESCRIPTION
**Pull request by phillipskevin**
First piece of https://github.com/canjs/canjs/issues/3147.

### CODE REVIEW

**Comment by phillipskevin** [comment]
@justinbmeyer any idea how I should test this?

**Comment by phillipskevin** [comment]
I'm just trying to determine if I should

1. not test this at all
2. use steal-clone to make sure the nodeList is passed to can-view-live
3. write a more realistic integration test to make sure the attribute event listener is removed if the nodeList is unregistered

**Comment by justinbmeyer** [comment]
Why is passing the nodeList needed? Doesn't the binding get torn down when the element is removed?

**Comment by phillipskevin** [comment]
The `attr` bindings were not being torn down. https://github.com/canjs/can-view-live/pull/29 is open to handle that, but it needs the nodeList.

**Comment by justinbmeyer** [comment]
Yeah, why were they not being torn down?  Is something wrong with the `.attr` that it's not listening to when the element is removed?

**Comment by phillipskevin** [comment]
Going to handle this differently.

**Pull request closed without merging**
