### PR TITLE
Fix #61 (first and last helpers in each loop)

### LINKED ISSUE #61: first and last helpers in each loop.
From: https://github.com/canjs/canjs/issues/2329

`%first` and `%last` that would be `true` or `false` if the index was right.

This could probably be done like:

```
{{#each items}}
  {{#eq @index items.length}}last{{/eq}}
{{/each}}
```

### PR DESCRIPTION
**Pull request by prashantsharmain**
Add support for %first and %last when looping over an array, object, can-list and can-map.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Thanks! Does this work in the `{{#each}}` helper too?

**Comment by prashantsharmain** [comment]
@justinbmeyer Yes, it would. I have added 3 new tests that would help illustrate the behavior.

**Comment by prashantsharmain** [comment]
@justinbmeyer Resolved merge conflicts and updated the PR. This is ready for review. Thanks.

**Comment by justinbmeyer** [comment]
Looks good.  This should go in `can-stache@3.1.0`.

**Comment by justinbmeyer** [comment]
Prashant, thanks for working on this.   Unfortunately, it doesn't work with live data like a `can.List`.  Changes to `can-view-live.list` are needed.

**Comment by justinbmeyer** [comment]
@prashantsharmain the test to add will be one that uses a DefineList and adds and removes items from it.  I can show you how to set this up in `can-view-live.list`.

**Comment by prashantsharmain** [comment]
@justinbmeyer Sorry about that. I'll check `can-view-live.list `and get back to you if I have questions.

**Pull request merged**
