### PR TITLE
Updated can-stache to be import stache from can-stache able

### PR DESCRIPTION
**Pull request by frank-dspeed**
Updated can-stache to be import stache from can-stache able

### CODE REVIEW

**Comment by justinbmeyer** [comment]
What Is this for? Why export with two different formats?

**Comment by matthewp** [comment]
This won't work. We either need this: https://github.com/stealjs/transpile/issues/73 to support ES modules or convert manually to ES and transpile to CJS.

**Comment by frank-dspeed** [comment]
@justinbmeyer because i regonized that i simply cant do import stache from can-stache and i corrected it tthis way in all my libs so i tought this will work here also.

**Comment by justinbmeyer** [comment]
@matthewp / @frank-dspeed why can't you do this?  Is this because ES6 syntax doesn't use the main export of a CJS module?

**Comment by justinbmeyer** [comment]
Closing until we figure out why this is needed.  @frank-dspeed it might help to create an issue for this first.

**Comment by matthewp** [comment]
From a steal perspective a module cannot have two formats, it cannot be both an ESM (having exports) and a CommonJS module. I think webpack supports this, but steal doesn't, the browser doesn't, and Node.js isn't going to.

**Comment by frank-dspeed** [comment]
@matthewp i use this tech normaly with babel and i tought steal can handle it maybe also with babel i get a import and require able lib as expected and with nodejs this worked  also.

- https://github.com/direktspeed/class-nonew-decorator
- https://github.com/direktspeed/serialport-parsers-cctalk/blob/master/dist/cctalk.js

**Pull request closed without merging**
